### ISSUE TITLE
Variável no Local Errado

### ISSUE THREAD

**Issue by HeberBarra** [MarioJunior01/CrudEstudantil#2]
Bom dia, na linha 83 da classe Programa Principal tem uma variável que não deveria estar ali, principalmente por estar direto no corpo da classe ao invés de estar de um método.

![image](https://github.com/user-attachments/assets/c134ebd1-d5a0-4730-8e06-72832e0c0063)

**Comment by MarioJunior01** [comment]
bom dia, obrigado erro arrumado.
