### ISSUE TITLE
Erros no código

### ISSUE THREAD

**Issue by HeberBarra** [MarioJunior01/CrudEstudantil#3]
A classe _Curso_ não deve possuir o atributo _quantidadeTurmas_, ainda na mesma classe, o atributo _duracaoCuros_ está escrito errado, e por que ele é LocalDate?
Na classe _ProgramaPrincipal_, as constantes estão escritas todas de forma errada, deve-se sempre colocar um _underline_( _ ) entre cada palavra, além deixar todas as letras maiúsculas. 
Não abrevie nome de variáveis, use _gerenciadorAluno_ ao invés de _gerAluno_.
A classe _ImpotadorArquivo_ provavelmente deverá ser renomeado, e o caminho utilizado não se enquadra na estrutura apropriada de um projeto java. Inclusive, diretórios devem terminar como uma barra ( / ) para deixar claro que são diretórios.
Por favor ajeite a formatação de todos os arquivos.

**Comment by MarioJunior01** [comment]
Obg heber

**Comment by HeberBarra** [comment]
De nada
